[package]
name = "aoc-util"
version = "0.1.0"
edition = "2021"
authors = [
    "Nico"
]
readme = "README.md"
description = "Utilities function for aoc"
license = "Apache-2.0"
repository = "https://github.com/nambrosini/aoc-util/"


[dependencies]
